name: Dependabot Auto-merge
on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: Auto-merge Dependabot PRs for minor and patch updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-patch' || steps.metadata.outputs.update-type == 'version-update:semver-minor'}}
        run: |
          echo "Auto-merging ${{ steps.metadata.outputs.dependency-names }}"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - name: Comment on major version updates
        if: ${{steps.metadata.outputs.update-type == 'version-update:semver-major'}}
        run: |
          gh pr comment "$PR_URL" --body "🚨 **Major version update detected!**
          
          This PR contains major version changes that may include breaking changes:
          - **Dependency**: ${{ steps.metadata.outputs.dependency-names }}
          - **Update type**: ${{ steps.metadata.outputs.update-type }}
          
          Please review this carefully before merging."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
