name: Docker Image CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Skip Docker push for Dependabot PRs (they don't have access to secrets)
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag envidtech/portfolio-website:latest

      - name: Push to Docker Hub
        run: docker push envidtech/portfolio-website:latest

  # Separate job for Dependabot PRs - build only (no push)
  build-only:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image (test only)
        run: docker build . --file Dockerfile --tag envidtech/portfolio-website:test